name: 'Pull Request Comment Environment Variables'
description: 'Set environment variables depending on pull request comments'
inputs:
  token:
    description: 'Token to access the pull request'
    required: true
  default_env:
    description: 'Default environment variables if they are not provided in the comment'
runs:
  using: 'node12'
  main: 'dist/index.js'