name: 'Pull Request Comment Environment Variables'
description: 'Set environment variables depending on pull request comments'
inputs:
  token:
    description: 'Token to access the pull request'
    required: true
  trigger:
    description: 'A comment that starts with the trigger word is considered as parameters'
    required: true
  default_env:
    description: 'Default environment variables if they are not provided in the comment'
runs:
  using: 'node12'
  main: 'index.js'