name: Get env vars from PR15

on: 
  workflow_dispatch:

jobs:
  get-env-var-from-test-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # The test PR: #15
          pull_request: 15
          default_env: 'FOO=1, BAR=2'
          debug: 'true'