on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Get env vars from PR15
          token: ${{ secrets.GITHUB_TOKEN }}

